### ISSUE TITLE
Code health tracker

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#1227]
## 🚀 Feature

List including the pending things to do to improve the package health

- [x] Add codespell in pre-commit
- [x] Add pyupgrade in pre-commit
- [x] Add dependabot -> already enabled!
- [x] Deepsource: https://deepsource.io/gh/kornia/kornia (need to find a proper way to automate)
- [x] docformatter: https://github.com/myint/docformatter
- [x] yesqa: https://github.com/asottile/yesqa
- [ ] full support to `bandit` -> https://github.com/kornia/kornia/issues/1245
- [x] configure dependabot to `requirements-dev.txt`
- [ ] flake8-bugbear https://github.com/kornia/kornia/pull/1233
- [ ] Pytest raises 600+ warnings https://github.com/kornia/kornia/issues/1225
- [ ] Tests take a long time https://github.com/kornia/kornia/discussions/1260

**Comment by edgarriba** [comment]
@cclauss I was following the dependabot tutorial and it's already enabled. By doing I found the code scanning alerts. Is it worth or do you have any suggestion about what API should we choose from the marketplace ?

**Comment by edgarriba** [comment]
In our case we do not have dependencies at all for the library - it's only pytorch. Or do you count also the development libraries ?

**Comment by cclauss** [comment]
You might point dependabot at PyPI projects like https://github.com/kornia/kornia/blob/master/requirements-dev.txt

**Comment by cclauss** [comment]
Dependabot can be checked above.

Also, Add #1260?

**Comment by johnnv1** [comment]
about the tests, the `tests_gradcheck` can be really slow, and just run with fp64. but right now we have pass the dtype fixture to them and cast it to fp64 with `testing.tensor_to_gradcheck_var` -- so, removing the `dtype` fixture from the `test_gradcheck`, may help to shorten the test suite time a bit

**Comment by cclauss** [comment]
My recommendation these daze is to replace bandit, flake8 plus plugins, isort, pylint with https://beta.ruff.rs which has 400+ Python linting rules and it is written in Rust so it does its work in pre-commit in a fraction of a second.

**Comment by johnnv1** [comment]
@edgarriba I pointed out some rules that maybe we can adopt from ruff (in #2358), should we reopen this issue for them, or do you think it makes more sense to have a new tracker? Since will be related to ruff itself, I think it makes more sense to be a new one 😄
