### ISSUE TITLE
Bandit - security linter issues tracker

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#1245]
## 🚀 Feature

We recently introduced Bandit - A security linter from PyCQA as part oof the CI/CD
https://github.com/PyCQA/bandit

See: https://github.com/kornia/kornia/blob/master/.pre-commit-config.yaml#L50-L58

## Motivation

We want kornia code to be clean of security issues. Ideally we want the following tests to pass:

- [x] B110 https://github.com/kornia/kornia/pull/1243
- [x] B101 https://github.com/kornia/kornia/pull/1248
- [x] B311 https://github.com/kornia/kornia/pull/1251
- [ ] B404
- [ ] B602
- [ ] B603
- [ ] B607

## Pitch

In order to reproduce the fixes make the following call:

```bash
bandit -r --tests B101 ./kornia
```

Where `B101` is any of the codes above.

**Comment by cclauss** [comment]
I recommend that we modify the command above to drop `./kornia` because we should be concerned about any security flaw that bandit identifies in any code in this repo.

**Comment by edgarriba** [comment]
@cclauss sure - but it's weird that in local it takes forever with your suggestion.

**Comment by cclauss** [comment]
Try `--skip=./.*` to keep bandit from looking thru .git, .venv, etc.

**Comment by edgarriba** [comment]
possibly we want to skip tests too ? e.g `B101:assert_used` and our testing is based in assertions

**Comment by cclauss** [comment]
`bandit --recursive --skip B101 .`

**Comment by edgarriba** [comment]
My point is that in some places like test we don’t want B101 but we do in the main directory of Kornia
