### ISSUE TITLE
Update configs to use `dataclasses`

### ISSUE THREAD

**Issue by johnnv1** [kornia/kornia#2093]
We have some specific configs for some algorithms, will be nice to update them from using `dicts`/`TypedDict` to `dataclasses`. 

The idea here is to do it in a way that does not break things, so we should have an interface (to/from) between `dict` and the `dataclasses`.

Example of what we can explore for these methods
```python
>>> from dataclasses import dataclass, asdict
>>> @dataclass
... class A:
...     b: int
... 
>>> asdict(A(1))
{'b': 1}
>>> A(**asdict(A(1)))
A(b=1)
```
_Originally posted by @johnnv1 in https://github.com/kornia/kornia/pull/2092#discussion_r1049564760_

List of some configs to be replaced:
 - [ ] kornia.feature.adalam.core.AdalamConfig
 - [ ] kornia.contrib.face_detection.FaceDetector.config #2851
 - [ ] kornia.feature.keynet.KeyNet_conf - #2254
 - [ ] [kornia.feature.loftr.loftr.default_cfg](https://github.com/kornia/kornia/blob/2387a2d165a977f1646332d6cbe6b915a4806e37/kornia/feature/loftr/loftr.py#L25)
   - [ ] kornia.feature.loftr.loftr_module.fine_preprocess.FinePreprocess.config
   - [ ] kornia.feature.loftr.loftr_module.transformer.LocalFeatureTransformer.config
   - [ ] kornia.feature.loftr.utils.coarse_matching.CoarseMatching.config
   - [ ] kornia.feature.loftr.utils.supervision config
   - [ ] [kornia.feature.loftr.backbone.resnet_fpn config](https://github.com/kornia/kornia/blob/2387a2d165a977f1646332d6cbe6b915a4806e37/kornia/feature/loftr/backbone/resnet_fpn.py#L50)
 - [ ] kornia.feature.matching._get_default_fginn_params
 - [ ] [kornia.feature.sold2.backbones.SOLD2Net.cfg](https://github.com/kornia/kornia/blob/2387a2d165a977f1646332d6cbe6b915a4806e37/kornia/feature/sold2/backbones.py#L377) - #2880
   - [ ] [kornia.feature.sold2.sold2.default_cfg](https://github.com/kornia/kornia/blob/2387a2d165a977f1646332d6cbe6b915a4806e37/kornia/feature/sold2/sold2.py#L18)
   - [ ] [kornia.feature.sold2.sold2_detector.default_cfg](https://github.com/kornia/kornia/blob/2387a2d165a977f1646332d6cbe6b915a4806e37/kornia/feature/sold2/sold2_detector.py#L17)

**Comment by edgarriba** [comment]
@ducha-aiki can you help to triage importance in the feature module. Also to audit if we eventually have things to deprecate etc

**Comment by Ikonsty** [comment]
@ johnnv1 Can I fix one of the files, for example, KeyNetConf, pull it, and if everything is okay, add more changes?

**Comment by johnnv1** [comment]
Go ahead, when the PR is ok for review you can ping me and @ducha-aiki for it 😄

**Comment by rajshukla1102** [comment]
hey @johnnv1 can you assign this to me

**Comment by johnnv1** [comment]
Go ahead, but if possible, open separate PRs for each feature

**Comment by rajshukla1102** [comment]
@johnnv1 Thank you! looking forward to completing this soon😊

**Comment by lappemic** [comment]
I've been reviewing the list of potential contributions and noticed that many tasks are either already completed or no longer relevant. However, I've identified a couple of areas where I believe I could contribute effectively:

- kornia.feature.matching._get_default_fginn_params
- kornia.feature.adalam.core.AdalamConfig

Could you please confirm if these contributions are still needed? I would appreciate any additional guidance or suggestions you might have on how to proceed.

Looking forward to your feedback!

**Comment by johnnv1** [comment]
> Could you please confirm if these contributions are still needed?

Sure it's, place a PR for this, and if you have any questions you can ping me at kornia slack

For cases like `AdalamConfig` which is a typed dict within `NoRequired`, you will need to check if we will need to initialize it somehow or not. Based on this, you'll be able to define the types, and if necessary you'll need to add some `isinstance` checks in some places

**Comment by lappemic** [comment]
In the #2880 the [kornia.feature.sold2.sold2_detector.default_cfg](https://github.com/kornia/kornia/blob/2387a2d165a977f1646332d6cbe6b915a4806e37/kornia/feature/sold2/sold2_detector.py#L17) the config is refactored. I therefore also looked into [kornia.feature.sold2.backbones.SOLD2Net.cfg](https://github.com/kornia/kornia/blob/2387a2d165a977f1646332d6cbe6b915a4806e37/kornia/feature/sold2/backbones.py#L377) and  [kornia.feature.sold2.sold2.default_cfg](https://github.com/kornia/kornia/blob/2387a2d165a977f1646332d6cbe6b915a4806e37/kornia/feature/sold2/sold2.py#L18):
- [kornia.feature.sold2.sold2.default_cfg](https://github.com/kornia/kornia/blob/2387a2d165a977f1646332d6cbe6b915a4806e37/kornia/feature/sold2/sold2.py#L18) uses the same `default_config` as in `SOLD2_detector` plus the `line_matcher_cfg`. Shall we put the `dataclass` definitions in a separate file (e.g. `sold2_dataclasses.py` in `utils`)? This way we could avoid repetition.

**Comment by johnnv1** [comment]
> Shall we put the `dataclass` definitions in a separate file (e.g. `sold2_dataclasses.py` in `utils`)? This way we could avoid repetition.

Yeap, the detector default config has the descriptor equals `False` different than other one. But you can unify it under a `structures.py` file in sold2 module ("kornia/feature/sold2/structures.py").

**Comment by Big-Marvel** [comment]
Hi @johnnv1 
Is this issue still open? If so, I would like to take this up.
