### ISSUE TITLE
 [ROADMAP] Kornia v0.1.6

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#385]
This is the roadmap for **kornia v0.1.6** that will focus mainly in morphology and epipolar geometry.

Feel free to volunteer yourself if you are interested in trying out some items(they do not have to be on the list). Please, take a read on the CONTRIBUTING notes.

* **Epipolar Geometry**
Propose stuff potentially from `opencv.calib3d` and `opencv.sfm`
  * [x] symmetrical_epipolar_distance https://github.com/kornia/kornia/pull/283 @ducha-aiki 
  * [x] sampson_epipolar_distance https://github.com/kornia/kornia/pull/283 @ducha-aiki 
  * [ ] find_fundamental @edgarriba 
  * [ ] find_homography @edgarriba 
  * [ ] compute_correspond_epilines @edgarriba 

* **Morphology** see discussion: https://github.com/kornia/kornia/issues/293#issuecomment-546725336
  * [ ] dilation https://github.com/kornia/kornia/pull/292
  * [ ] erosion
  * [ ] open
  * [ ] close
  * [ ] skeleton
  * [ ] morphological edge detection
  * [ ] histogram https://github.com/kornia/kornia/issues/413

* **Differentiable drawing**. To be defined. Please, propose.

* **Model Zoo** *. To be discussed, use `torch.hub`
  * [ ] HardNet : https://github.com/DagnyT/hardnet

### Improvements
Please propose whatever feature you consider is missing.

* **kornia.augmentation**. 
  * [ ] Grayscale @dvd42 

* **kornia.color**. 
  * [ ] lab_to_rgb https://github.com/kornia/kornia/issues/239 @HassanAlsamahi 
  * [ ] rgb_to_lab https://github.com/kornia/kornia/issues/239 @HassanAlsamahi 
  * [ ] rgb_to_xyz
  * [ ] xyz_to_rgb
  * [ ] rgb_to_luv
  * [ ] luv_to_ rgb

* **Tests**
  * [ ] setup AWS CI @edgarriba @chadell
  * [ ] JIT tests https://github.com/kornia/kornia/pull/261

* **Documentation**
  * Improve tutorials/examples
  * Start using sphinx-doctest https://github.com/kornia/kornia/issues/422
