### ISSUE TITLE
[ROADMAP] Kornia v0.2.1

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#434]
This is the roadmap for **kornia v0.2.1** that will focus mainly in morphology and epipolar geometry.

Feel free to volunteer yourself if you are interested in trying out some items(they do not have to be on the list). Please, take a read on the CONTRIBUTING notes.

* **Epipolar Geometry**
Propose stuff potentially from `opencv.calib3d` and `opencv.sfm`
  * [x] symmetrical_epipolar_distance https://github.com/kornia/kornia/pull/283 @ducha-aiki 
  * [x] sampson_epipolar_distance https://github.com/kornia/kornia/pull/283 @ducha-aiki 
  * [x] find_fundamental @edgarriba 
  * [x] find_homography @edgarriba 
  * [ ] compute_correspond_epilines @edgarriba 

* **Morphology** see discussion: https://github.com/kornia/kornia/issues/293#issuecomment-546725336
  * [ ] dilation https://github.com/kornia/kornia/pull/292
  * [ ] erosion
  * [ ] open
  * [ ] close
  * [ ] skeleton
  * [ ] morphological edge detection
  * [ ] histogram https://github.com/kornia/kornia/issues/413

* **KMeans**
  * [ ] @subhadarship https://github.com/subhadarship/kmeans_pytorch/issues/2

* **Differentiable drawing**. To be defined. Please, propose.

* **Model Zoo** *. To be discussed, use `torch.hub`
  * [x] HardNet : https://github.com/DagnyT/hardnet

### Improvements
Added features from [albumentations](https://github.com/albumentations-team/albumentations), please propose whatever feature you consider is missing or might relevant for next versions. Most functions are already available, or can be implemented using kornia core operators. Need a common interface.

* **kornia.augmentation**. 
  * [x] RandomMotionBlur https://github.com/kornia/kornia/issues/494
  * [ ] Grayscale @dvd42 
  * [ ] ElasticTransformation [[link]](https://github.com/pytorch/vision/pull/1448/files)
  * [ ] Blur [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.Blur)
  * [ ] Transpose [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.Transpose)
  * [ ] RandomGamma [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.RandomGamma)
  * [ ] RandomRotate90 [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.RandomRotate90)
  * [ ] MedianBlur [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.MedianBlur)
  * [ ] GaussianBlur [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.GaussianBlur)
  * [ ] GaussNoise [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.GaussNoise)
  * [ ] GlassBlur [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.GlassBlur)
  * [ ] CLAHE [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.CLAHE)
  * [ ] ChannelShuffle [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.ChannelShuffle)
  * [ ] rgb_to_sepia [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.ToSepia)
  * [ ] RandomSnow [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.RandomSnow)
  * [ ] RandomRain [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.RandomRain)
  * [ ] RandomFog [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.RandomFog)
  * [ ] RandomSunFlare [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.RandomSunFlare)
  * [ ] RandomShadow [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.RandomShadow)
  * [ ] Solarize [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.Solarize)
  * [x] Equalize [[link]](https://albumentations.readthedocs.io/en/latest/api/augmentations.html#albumentations.augmentations.transforms.Equalize)

* **kornia.filter**. 
  * [ ] GaussianBlur3d @edgarriba 

* **kornia.feature**. 
  * [ ] DenseSIFT @ducha-aiki https://github.com/kornia/kornia/issues/462 

* **kornia.color**. 
  * [ ] lab_to_rgb https://github.com/kornia/kornia/issues/239 @HassanAlsamahi 
  * [ ] rgb_to_lab https://github.com/kornia/kornia/issues/239 @HassanAlsamahi 
  * [x] rgb_to_xyz @ceroytres https://github.com/kornia/kornia/pull/436
  * [x] xyz_to_rgb @ceroytres https://github.com/kornia/kornia/pull/436
  * [x] rgb_to_luv @ceroytres https://github.com/kornia/kornia/pull/442
  * [x] luv_to_ rgb @ceroytres https://github.com/kornia/kornia/pull/442
  * [ ] ZCA Whitening https://github.com/kornia/kornia/issues/435 TBD

* **Tests**
  * [ ] setup AWS CI @edgarriba @chadell
  * [ ] JIT tests https://github.com/kornia/kornia/pull/261

* **Documentation**
  * Improve tutorials/examples
  * Start using sphinx-doctest https://github.com/kornia/kornia/issues/422

**Comment by ceroytres** [comment]
@edgarriba Can I do the remaining color conversions?

**Comment by edgarriba** [comment]
@ceroytres sure, go ahead, try to split them in different PRs

**Comment by humandotlearning** [comment]
@edgarriba I see Lab <-> RGB is pending for a while can I complete it?

**Comment by edgarriba** [comment]
@humandotlearning yes, please go ahead

**Comment by ceroytres** [comment]
@edgarriba I can work on zca whitening #435. I was hoping to push a RGB<->sRGB converter since it's used both by Luv and Lab in OpenCV [here](https://github.com/opencv/opencv/blob/b39cd06249213220e802bb64260727711d9fc98c/modules/imgproc/src/color.hpp#L84), [here1](https://github.com/opencv/opencv/blob/8c0b0714e76efef4a8ca2a7c410c60e55c5e9829/modules/imgproc/src/color.cpp#L271). Maybe @humandotlearning can wait for me to push it out so he can used it  in his Lab function?

**Comment by edgarriba** [comment]
@ceroytres go ahead with zca whitening. Make a bit of research about how it should be done, I remember to not go that deep with that ;)

**Comment by ucalyptus** [comment]
@edgarriba can I take up histogram?

**Comment by edgarriba** [comment]
@ucalyptus sure, go ahead.

**Comment by connorlee77** [comment]
@ucalyptus Have you made any progress on histogram? I am wondering how you computed a 2d histogram in pytorch.

**Comment by edgarriba** [comment]
@connorlee77 check https://github.com/kornia/kornia/issues/413 and move this discussion over there. Feel free to volunteer for any task

**Comment by miriaford** [comment]
Hi, thanks for making this wonderful library! Do you have any new progress or ETA for the list of `kornia.augmentation` above? 
The main downside that keeps me away from `Albumentation` is the lack of GPU support and the fact that I have to convert tensor back to PIL before the operations. I'd love to see Kornia supporting most of `albumentation` op in GPU batch mode. ;)

**Comment by edgarriba** [comment]
@miriaford next milestone for `kornia.augmentation` is towards this direction. We'll go case by case - any specific priority requirement that could help to define the next roadmap ? /cc @shijianjian

**Comment by miriaford** [comment]
Thanks for your timely reply! I'm looking specifically to reproduce the pipeline in the [AutoAugment paper](https://arxiv.org/abs/1805.09501), screenshot below. 

It'd be great if these functions could be implemented first: `Solarize`, `Equalize`, `Posterize`, `Sharpness`.

![image](https://user-images.githubusercontent.com/29965840/80745994-033a2c80-8ad6-11ea-8fb4-5d8a80e7382a.png)

**Comment by edgarriba** [comment]
sounds like a plan

**Comment by simionAndrei** [comment]
@edgarriba At the moment, is there any implementation for torchvision.transform.RandomApply? Or any workaround to implement RandomApply with the existing API?

**Comment by shijianjian** [comment]
> It'd be great if these functions could be implemented first: `Solarize`, `Equalize`, `Posterize`, `Sharpness`.

Hi @miriaford, those functionalities have been implemented and probably be included in the next release. You may try it out now. Sorry for taking too much time on it.

If possible, we are very happy to see an Autoaugmentation example of using Kornia. :)
