### ISSUE TITLE
[ROADMAP] Kornia v0.5.0

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#700]
This is the roadmap for **kornia v0.5** that will focus on the package stability.

Expected date release: _mid-November according to PyTorch v1.7._

Check the [PROJECT](https://github.com/kornia/kornia/projects/6) tab and feel free to volunteer yourself if you are interested in trying out some items.
Please, take a read on the [CONTRIBUTING](https://github.com/kornia/kornia/blob/master/CONTRIBUTING.rst) notes.

* **General**
  * [x] update to PyTorch v1.7 @edgarriba 
  * [ ] support 100% JIT [@all]
  * [x] Increase coverage > 95% @[all]
  * [x] Automate GPU tests and improve CI time @edgarriba @shijianjian 
  * [x] Refactor testing framework @FGeri @shijianjian https://github.com/kornia/kornia/issues/670
  * [x] Reorganise warping module @edgarriba https://github.com/kornia/kornia/issues/487

* **kornia.augmentation**
  * [ ] provide PIL-like interface for color transforms https://github.com/kornia/kornia/issues/565

* **kornia.features**
  * [ ] matching: implement optimal matcher from SuperGlue @ducha-aiki  ?
  * [x] local features: add MKD descriptor https://github.com/kornia/kornia/pull/718 @manyids2 

* **kornia.flters**
  * [x] Discrete Gaussian filter https://github.com/kornia/kornia/issues/559

**Comment by shijianjian** [comment]
BTW, I will be working on #520 shortly.

---

>   * [ ]  update to PyTorch v1.7

We should also put "supporting all torch versions" into the list as well. It will be a must I suppose, especially when we get more users. I do not want to alter my torch version when installing kornia. The easiest approach I can think of is to use:
```python
if torch.__version__ == '1.5.0':
    DO SOMETHING
elif  torch.__version__ == '1.6.0':
    DO SOMETHING
```

>   * [ ]  provide PIL-like interface for color transforms #565

Probably a global switch like ```K.augmentation.backend='opencv'``` and ```K.augmentation.backend='PIL'```?

**Comment by edgarriba** [comment]
Closing in favour of https://github.com/kornia/kornia/issues/930
