### ISSUE TITLE
[ROADMAP] Kornia v0.6

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#930]
This is the roadmap for **Kornia v0.6** that mainly will focus in the following highlight features:
- Add more functionalities for `kornia.augmentations` and refactor the backend pipeline to support Torchscript.
- Improve the `kornia.color` module  adding more functionality with losses.
- Include `kornia.nn` module to wrap functionals as torch modules.

Feel free to volunteer yourself if you are interested in trying out some items(they do not have to be on the list).
Please, take a read on the [CONTRIBUTING](https://github.com/kornia/kornia/blob/master/CONTRIBUTING.rst) notes.

* **kornia.color**
* [ ] Implement DeltaE - Ciede2000 to measure L2 in Lab space https://github.com/kornia/kornia/issues/929 @cceyda
* [ ] Add rgb to grayscale interface with custom weights
* [ ] Improve stability for HSV during backprop
* [ ] Add support to ICTP color space
* [ ] Add support to other color representations YUV 420, 444

* **Fix critical bugs**
* [ ] `RandomResizedCrop` https://github.com/kornia/kornia/issues/927
