### ISSUE TITLE
[Feat] Kornia color modules

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#935]
## 🚀 Feature

List of potential features for the `kornia.color` module:

- [ ] Implement DeltaE - Ciede2000 to measure L2 in Lab space #929 @cceyda
- [ ] Add rgb to grayscale interface with custom weights https://github.com/kornia/kornia/issues/931
- [ ] Improve stability for HSV during backprop https://github.com/kornia/kornia/issues/932
- [ ] Add support to ICTP color space https://github.com/kornia/kornia/issues/933
- [ ] Add support to other color representations YUV 420, 444 https://github.com/kornia/kornia/issues/934

**Please, check other libraries and propose more functionalities:**
- https://github.com/colour-science/colour <- :robot: 
- https://scikit-image.org/
